

[package]
name = "objr_procmacro"
version = "1.0.0"
authors = ["Drew Crawford <drew@sealedabstract.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"


[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
